<?php

/**
 * StdResult
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StdResult extends BaseStdResult {

    /**
     * Get STD episode hisotry
     * @return $episodeHistory
     */
    public function getEpisodeHistory() {
        try {

            $q = Doctrine_Query::create()
                    ->from('StdResult r')
                    ->where('r.patient_no = ?', $this->getPatientNo())
                    ->andWhere('r.episode_no = ?', $this->getEpisodeNo());

            $episodeHistory =$q->fetchArray();

            return $episodeHistory;

        } catch (Exception $e) {

            throw new Exception($e->getMessage());

        }

    }

     /**
     * Get STD episode results without result code
     * @return $stdResult
     */
    public function getStdEpisodeResultObjectWithoutResultCode() {

        try {

            $q = Doctrine_Query::create()
                    ->from('StdResult r')
                    ->where('r.patient_no = ?', $this->getPatientNo())
                    ->andWhere('r.episode_no = ?', $this->getEpisodeNo())
                    ->andWhere('r.input_code = ?', $this->getInputCode());

            $stdResult = $q->execute();

            return $stdResult;

        } catch (Exception $e) {

            throw new Exception($e->getMessage());
        }
    }

     /**
     * Get STD episode results with result code
     * @return $stdResult
     */
    public function getStdEpisodeResultObjectWithResultCode() {

        try {

            $stdResult = Doctrine::getTable('StdResult ')
                    ->find($this->getPatientNo(), $this->getEpisodeNo(), $this->getInputCode(), $this->getResultCode());

            return $stdResult;

        } catch (Exception $e) {

            throw new Exception($e->getMessage());
        }
    }

     /**
     * Get STD episode results array
     * @return $stdResult
     */
    public function getStdEpisodeResulArraytWithoutResultCode($patientNo, $episodeNo, $inputCode) {

        try {

            $q = Doctrine_Query::create()
                    ->from('StdResult r')
                    ->where('r.patient_no = ?', $patientNo)
                    ->andWhere('r.episode_no = ?', $episodeNo)
                    ->andWhere('r.input_code = ?', $inputCode);

            $stdResult = $q->fetchArray();

            return $stdResult;

        } catch (Exception $e) {

            throw new Exception($e->getMessage());
        }
    }

     /**
     * Delte STD episode results 
     * @param $patientNo, $episodeNo, $inputCode
     *  
     */
    public function deleteStdEpisodeResult($patientNo, $episodeNo, $inputCode) {

        try {

            $deleted = Doctrine_Query::create()
                    ->delete()
                    ->from('StdResult r')
                    ->where('r.patient_no = ?', $patientNo)
                    ->andWhere('r.episode_no = ?', $episodeNo)
                    ->andWhere('r.input_code = ?', $inputCode)
                    ->execute();



        } catch (Exception $e) {

            throw new Exception($e->getMessage());
        }
    }

    

}
