<?php

/**
 * SysModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pims
 * @subpackage model
 * @author     Shashimal Warakagoda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SysModule extends BaseSysModule {
    
    /**
     * Get module List
     * @return $moduleList 
     */
    public function getModuleList($assignedModuleRights) {
        
        $existingModules		=	$assignedModuleRights;
        $existingModule		=	array();
       	   	    
	    foreach($existingModules as $right) {
	        
        		array_push($existingModule, $right['module_id']);
        }
	    	
       $q = Doctrine_Query::create()
			 ->from('SysModule m')
			 ->whereNotIn('m.module_id',$existingModule)
			 ->orderBy('module_id ASC');
		
	    $moduleList = $q->execute();
			  
		return  $moduleList ;
    }
    
	/**
     * Get module rights 
     * @return Skill 
     */
    public function getUserGroupModelRights($userGroupID)
    {
   	 	try
        {
	    	$q = Doctrine_Query::create()
			    ->from('Rights')
			    ->where("user_group_id ='".$userGroupID."'");
			
			$rightList = $q->execute();
			  
			return  $rightList ;
			
        }catch( Exception $e)
        {
            throw new Exception($e->getMessage());
        }
    }
}
