<?php

/**
 * TraceContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TraceContact extends BaseTraceContact {
    
    /**
     * Trace contact details
     * @param $patientNo
     * @return $contact
     */
    public function getTracedContatDetails($patientNo) {
        
     try {

            $q = Doctrine_Query::create()
                    ->from('TraceContact t')
                    ->where('t.patient_no = ?', $patientNo)
                    ->orderBy('t.patient_no');

            $contact = $q->fetchArray();

            return $contact;

        } catch (Exception $e) {

            throw new Exception($e->getMessage());
        }
    }
}
