<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Episode', 'doctrine');

/**
 * BaseEpisode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $episode_no
 * @property string $patient_no
 * @property integer $status
 * @property string $comment
 * @property date $start_date
 * @property date $end_date
 * @property string $std_positive
 * @property string $hiv_positive
 * @property Patient $Patient
 * @property Doctrine_Collection $ClinicReason
 * @property Doctrine_Collection $Visit
 * 
 * @method integer             getEpisodeNo()    Returns the current record's "episode_no" value
 * @method string              getPatientNo()    Returns the current record's "patient_no" value
 * @method integer             getStatus()       Returns the current record's "status" value
 * @method string              getComment()      Returns the current record's "comment" value
 * @method date                getStartDate()    Returns the current record's "start_date" value
 * @method date                getEndDate()      Returns the current record's "end_date" value
 * @method string              getStdPositive()  Returns the current record's "std_positive" value
 * @method string              getHivPositive()  Returns the current record's "hiv_positive" value
 * @method Patient             getPatient()      Returns the current record's "Patient" value
 * @method Doctrine_Collection getClinicReason() Returns the current record's "ClinicReason" collection
 * @method Doctrine_Collection getVisit()        Returns the current record's "Visit" collection
 * @method Episode             setEpisodeNo()    Sets the current record's "episode_no" value
 * @method Episode             setPatientNo()    Sets the current record's "patient_no" value
 * @method Episode             setStatus()       Sets the current record's "status" value
 * @method Episode             setComment()      Sets the current record's "comment" value
 * @method Episode             setStartDate()    Sets the current record's "start_date" value
 * @method Episode             setEndDate()      Sets the current record's "end_date" value
 * @method Episode             setStdPositive()  Sets the current record's "std_positive" value
 * @method Episode             setHivPositive()  Sets the current record's "hiv_positive" value
 * @method Episode             setPatient()      Sets the current record's "Patient" value
 * @method Episode             setClinicReason() Sets the current record's "ClinicReason" collection
 * @method Episode             setVisit()        Sets the current record's "Visit" collection
 * 
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEpisode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('episode');
        $this->hasColumn('episode_no', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('patient_no', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('comment', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('start_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('std_positive', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('hiv_positive', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Patient', array(
             'local' => 'patient_no',
             'foreign' => 'patient_no'));

        $this->hasMany('ClinicReason', array(
             'local' => 'episode_no',
             'foreign' => 'episode_no'));

        $this->hasMany('Visit', array(
             'local' => 'episode_no',
             'foreign' => 'episode_no'));
    }
}