<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PatientNoTracker', 'doctrine');

/**
 * BasePatientNoTracker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $year
 * @property integer $male
 * @property integer $female
 * 
 * @method integer          getYear()   Returns the current record's "year" value
 * @method integer          getMale()   Returns the current record's "male" value
 * @method integer          getFemale() Returns the current record's "female" value
 * @method PatientNoTracker setYear()   Sets the current record's "year" value
 * @method PatientNoTracker setMale()   Sets the current record's "male" value
 * @method PatientNoTracker setFemale() Sets the current record's "female" value
 * 
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatientNoTracker extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patient_no_tracker');
        $this->hasColumn('year', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('male', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('female', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}