<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Uniqueid', 'doctrine');

/**
 * BaseUniqueid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $last_id
 * @property string $tbl
 * @property string $tbl_column
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method integer  getLastId()     Returns the current record's "last_id" value
 * @method string   getTbl()        Returns the current record's "tbl" value
 * @method string   getTblColumn()  Returns the current record's "tbl_column" value
 * @method Uniqueid setId()         Sets the current record's "id" value
 * @method Uniqueid setLastId()     Sets the current record's "last_id" value
 * @method Uniqueid setTbl()        Sets the current record's "tbl" value
 * @method Uniqueid setTblColumn()  Sets the current record's "tbl_column" value
 * 
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUniqueid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uniqueid');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('last_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tbl', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('tbl_column', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}