<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserGroup', 'doctrine');

/**
 * BaseUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_group_id
 * @property string $user_group_name
 * @property string $description
 * @property Doctrine_Collection $Rights
 * @property Doctrine_Collection $User
 * 
 * @method string              getUserGroupId()     Returns the current record's "user_group_id" value
 * @method string              getUserGroupName()   Returns the current record's "user_group_name" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getRights()          Returns the current record's "Rights" collection
 * @method Doctrine_Collection getUser()            Returns the current record's "User" collection
 * @method UserGroup           setUserGroupId()     Sets the current record's "user_group_id" value
 * @method UserGroup           setUserGroupName()   Sets the current record's "user_group_name" value
 * @method UserGroup           setDescription()     Sets the current record's "description" value
 * @method UserGroup           setRights()          Sets the current record's "Rights" collection
 * @method UserGroup           setUser()            Sets the current record's "User" collection
 * 
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group');
        $this->hasColumn('user_group_id', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('user_group_name', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('description', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rights', array(
             'local' => 'user_group_id',
             'foreign' => 'user_group_id'));

        $this->hasMany('User', array(
             'local' => 'user_group_id',
             'foreign' => 'user_group_id'));
    }
}