<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StdInputResult', 'doctrine');

/**
 * BaseStdInputResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $input_result_code
 * @property string $result_description
 * @property string $input_code
 * @property StdInput $StdInput
 * @property Doctrine_Collection $StdResult
 * 
 * @method integer             getInputResultCode()    Returns the current record's "input_result_code" value
 * @method string              getResultDescription()  Returns the current record's "result_description" value
 * @method string              getInputCode()          Returns the current record's "input_code" value
 * @method StdInput            getStdInput()           Returns the current record's "StdInput" value
 * @method Doctrine_Collection getStdResult()          Returns the current record's "StdResult" collection
 * @method StdInputResult      setInputResultCode()    Sets the current record's "input_result_code" value
 * @method StdInputResult      setResultDescription()  Sets the current record's "result_description" value
 * @method StdInputResult      setInputCode()          Sets the current record's "input_code" value
 * @method StdInputResult      setStdInput()           Sets the current record's "StdInput" value
 * @method StdInputResult      setStdResult()          Sets the current record's "StdResult" collection
 * 
 * @package    pims
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStdInputResult extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('std_input_result');
        $this->hasColumn('input_result_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('result_description', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('input_code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('StdInput', array(
             'local' => 'input_code',
             'foreign' => 'input_code'));

        $this->hasMany('StdResult', array(
             'local' => 'input_result_code',
             'foreign' => 'result_code'));
    }
}